### ISSUE TITLE
Official Staff Photos for Directory

### ISSUE THREAD

**Issue by sahwho** [mbhs/mbhs#22]
There are a few teachers for whom images are missing or an unofficial photo is used (myself, foster, mr. murley, new staff, etc.) . I don't know where the photos are being pulled from, but I saw there's an AWS bucket where they're stored. 

Can these be updated? I thought I'd submit a PR but seems like the photos just need to be updated.

**Comment by sahwho** [comment]
@m3ru @yinazhou008

**Comment by yinazhou008** [comment]
@sahwho thx for ping. just strolled through strapi's media library and found foster so that was an easy fix. for some reason your pic isn't here rn

**Comment by m3ru** [comment]
Can be updated - maybe someone can do this on Monday
